const userRoles = {
  admin: [
    'searchStudent',
    'createStudent',
    'createStaff',
    'createAdmin',
    'readStudent',
    'updateStudent',
    'deleteStudent',
    'readStudents',
    'readStaff',
    'deleteStaff',
    'updateStaff',
    'createCourse',
    'readCourse',
    'readCourses',
    'deletecourse',
    'updateCourse',
    'createClass',

    'readClass',
    'deleteClass',
    'updateClass',
    'createCourseData',
    'getCoursesScheme',
    'updateScheme',
    'getExams',
    'createRole',
    'readRoles',
    'createUserRole',
    'createAdmin',
    'getExamSummary',
    'teacherCourse',
  ],
  staff: [
    'searchStudent',
    'readStudent',
    'readStudents',
    'updateCourse',
    'createClass',
    'teacherCourse',
    'readCourses',
    'readClass',
    'updateScheme',
    'getCoursesScheme',
    'createExam',
    'updateExam',
    'deleteExam',
    'createQuestion',
    'updateQuestion',
    'deleteQuestion',
    'createOption',
    'updateOption',
    'deleteOption',
    'createGrade',
    'createAttendance',
    'createUserRole',
    'getExamSummary',
  ],
  pupil: ['readStudent', 'readCourses', 'createAnswer', 'updateAnswer'],
};

module.exports = userRoles;
